// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Api.Data;

#nullable disable

namespace TicTacToe.Api.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    partial class GamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("TicTacToeGame.Models.GameCell", b =>
                {
                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Variant")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameSessionId", "Position");

                    b.ToTable("GameCells", (string)null);
                });

            modelBuilder.Entity("TicTacToeGame.Models.GameSession", b =>
                {
                    b.Property<int>("GameSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Player1PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Player2PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerTurnPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameSessionId");

                    b.HasIndex("Player1PlayerId");

                    b.HasIndex("Player2PlayerId");

                    b.HasIndex("PlayerTurnPlayerId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("TicTacToeGame.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Variant")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("TicTacToeGame.Models.GameCell", b =>
                {
                    b.HasOne("TicTacToeGame.Models.GameSession", null)
                        .WithMany("Cells")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicTacToeGame.Models.GameSession", b =>
                {
                    b.HasOne("TicTacToeGame.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1PlayerId");

                    b.HasOne("TicTacToeGame.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2PlayerId");

                    b.HasOne("TicTacToeGame.Models.Player", "PlayerTurn")
                        .WithMany()
                        .HasForeignKey("PlayerTurnPlayerId");

                    b.HasOne("TicTacToeGame.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("PlayerTurn");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TicTacToeGame.Models.GameSession", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
